In [229]:
from sklearn import datasets
import pandas as pd
import numpy as np

from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder, FunctionTransformer
from sklearn.metrics import f1_score, plot_confusion_matrix, confusion_matrix
from sklearn.compose import ColumnTransformer

from imblearn.pipeline import Pipeline as imbPipeline

from category_encoders import TargetEncoder

import warnings
warnings.filterwarnings('ignore')

In [124]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [125]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [112]:
df = pd.DataFrame(X)
df1 = pd.DataFrame(y, columns=['target'])

In [113]:
df = df.join(df1)

In [114]:
X = df.drop('target', axis=1)
y = [df.target]

In [128]:
y.reshape(1,-1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [129]:
#ohe = OneHotEncoder()
#y_encoded = ohe.fit_transform([y])

In [130]:
dummy_y = np_utils.to_categorical(y)

In [131]:
dummy_y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [132]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [133]:
# Compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [135]:
model.fit(X, dummy_y, epochs=50, batch_size=5)

Epoch 1/50
30/30 [==============================] - 0s 2ms/step - loss: 2.2177 - accuracy: 0.3333
Epoch 2/50
30/30 [==============================] - 0s 1ms/step - loss: 1.6723 - accuracy: 0.3333
Epoch 3/50
30/30 [==============================] - 0s 2ms/step - loss: 1.3490 - accuracy: 0.3333
Epoch 4/50
30/30 [==============================] - 0s 1ms/step - loss: 1.2158 - accuracy: 0.3333
Epoch 5/50
30/30 [==============================] - 0s 2ms/step - loss: 1.1531 - accuracy: 0.3333
Epoch 6/50
30/30 [==============================] - 0s 1ms/step - loss: 1.1080 - accuracy: 0.3400
Epoch 7/50
30/30 [==============================] - 0s 2ms/step - loss: 1.0572 - accuracy: 0.3400
Epoch 8/50
30/30 [==============================] - 0s 2ms/step - loss: 1.0186 - accuracy: 0.3600
Epoch 9/50
30/30 [==============================] - 0s 2ms/step - loss: 0.9749 - accuracy: 0.3467
Epoch 10/50
30/30 [==============================] - 0s 2ms/step - loss: 0.9366 - accuracy: 0.4000
Epoch 11/50
30/30 [

# Neural Network

In [226]:
X_train = pd.read_csv('Data/X_train.csv', index_col='building_id')
X_test = pd.read_csv('Data/X_test.csv', index_col='building_id')
y_train = pd.read_csv('Data/y_train.csv', index_col='building_id')
y_test = pd.read_csv('Data/y_test.csv', index_col='building_id')

In [143]:
y_train.values.reshape(1, -1)

array([[2, 2, 2, ..., 2, 3, 2]])

In [165]:
y_train['target'] = y_train.damage_grade.apply(lambda x: x - 1)

In [178]:
dummy_y_train = np_utils.to_categorical(y_train.target)

In [179]:
dummy_y_train.shape

(195450, 3)

### Column Transformer

In [217]:
binary_cols = []
for col in X_train.columns:
    if col.startswith('has'):
        binary_cols.append(col)

cat_cols = list(X_train.select_dtypes(include='object').columns)

integer_cols = ['count_floors_pre_eq', 'age', 'area_percentage', 'height_percentage', 'count_families']

geo_cols = ['geo_level_1_id', 'geo_level_2_id', 'geo_level_3_id']

all_cols = geo_cols + cat_cols + integer_cols + binary_cols

In [218]:
binary_cols_dropped = binary_cols.copy()
for col in binary_cols_dropped:
    if col.startswith('has_secondary'):
        binary_cols_dropped.remove(col)
binary_cols_dropped.append('has_secondary_use')

cat_cols_dropped = cat_cols.copy()
cat_cols_dropped.remove('legal_ownership_status')
cat_cols_dropped.remove('plan_configuration')

In [219]:
def log_transform(x):
    return np.log(x+1)

In [224]:
function_transformer = FunctionTransformer(log_transform)

ohe_pipe = imbPipeline([('ohe', OneHotEncoder(sparse=False, handle_unknown='ignore'))])
integer_pipe = imbPipeline([
    ('function', function_transformer),
    ('ss', StandardScaler())
])
target_pipe = imbPipeline([('target', TargetEncoder(cols=geo_cols))])

transformer = ColumnTransformer([
    ('binary', 'passthrough', binary_cols_dropped),
    ('categorical', ohe_pipe, cat_cols_dropped),
    ('geo', target_pipe, geo_cols),
    ('integer', integer_pipe, integer_cols),
])

In [230]:
transformed_X_train = transformer.fit_transform(X_train, y_train)

In [232]:
transformed_X_train.shape

(195450, 49)

In [234]:
model = Sequential()
model.add(Dense(8, input_dim=49, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [235]:
# Compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [237]:
model.fit(transformed_X_train, dummy_y_train, epochs=50, batch_size=1000)

Epoch 1/50
196/196 [==============================] - 0s 1ms/step - loss: 0.8871 - accuracy: 0.5528
Epoch 2/50
196/196 [==============================] - 0s 1ms/step - loss: 0.7773 - accuracy: 0.6382
Epoch 3/50
196/196 [==============================] - 0s 1ms/step - loss: 0.7283 - accuracy: 0.6790
Epoch 4/50
196/196 [==============================] - 0s 1ms/step - loss: 0.6850 - accuracy: 0.7081
Epoch 5/50
196/196 [==============================] - 0s 1ms/step - loss: 0.6480 - accuracy: 0.7244
Epoch 6/50
196/196 [==============================] - 0s 1ms/step - loss: 0.6218 - accuracy: 0.7326
Epoch 7/50
196/196 [==============================] - 0s 1ms/step - loss: 0.6059 - accuracy: 0.7362
Epoch 8/50
196/196 [==============================] - 0s 1ms/step - loss: 0.5966 - accuracy: 0.7387
Epoch 9/50
196/196 [==============================] - 0s 2ms/step - loss: 0.5911 - accuracy: 0.7404
Epoch 10/50
196/196 [==============================] - 0s 2ms/step - loss: 0.5877 - accuracy: 0.7426

### Transform X_test

In [238]:
transformed_X_test = transformer.transform(X_test)

In [239]:
y_pred = model.predict_classes(transformed_X_test)

In [240]:
y_pred_df = pd.DataFrame(y_pred, columns=['y_pred_adj'], index=X_test.index)

In [241]:
y_pred_df['y_pred'] = y_pred_df['y_pred_adj'].apply(lambda x: x + 1)

In [242]:
y_pred_df

y_pred_adj  y_pred
building_id                    
709407                1       2
586623                1       2
710592                1       2
343630                1       2
42427                 2       3
...                 ...     ...
708773                2       3
444011                2       3
78354                 2       3
338761                0       1
1000869               1       2

[65151 rows x 2 columns]

In [243]:
keras_score = f1_score(y_test, y_pred_df.y_pred, average='micro')
keras_score

0.7317769489340148